# fly.toml app configuration file generated for agnos on 2023-06-19T14:25:15+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "agnos"
primary_region = "cdg"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
